/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Clases.ClsCandidato;
import Clases.ClsVotante;
import Controladores.CtlCandidato;
import Controladores.CtlVotante;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leine
 */
public class FrameVotar extends javax.swing.JFrame {

    CtlCandidato controladorcandidato;
    CtlVotante controladorVotante;
    LinkedList<ClsCandidato> listaCandidatos;
    LinkedList<ClsVotante> listaVotantes;
    JFrame FrameMenu;

    /**
     * Creates new form FrameVotar
     */
    public FrameVotar(String id) {
        initComponents();
        //
        this.controladorcandidato = new CtlCandidato();
        this.controladorVotante = new CtlVotante();

        this.llamarcandidato();
        this.llamarvotante();
        this.numeroVota.setText(id);
        this.numeroVota.setEnabled(false);
        this.FrameMenu = new FrameMenu();
        //this.buscarVotante(id);
    }

    public void buscarvotante(String id) {

        this.numeroVota.setText(id);
        this.numeroVota.setEnabled(false);
        ClsVotante votante = this.buscarVotante(id);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel = new javax.swing.JPanel();
        candiRegistrado = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVotar = new javax.swing.JTable();
        votarCandi = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        img_registraduria = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        numeroVota = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        panel.setBackground(new java.awt.Color(255, 255, 255));

        tablaVotar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Partido", "Cedula Candidato", "Sms Campaña"
            }
        ));
        jScrollPane1.setViewportView(tablaVotar);

        candiRegistrado.addTab("Candidatos registrados", jScrollPane1);

        votarCandi.setText("Votar");
        votarCandi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                votarCandiActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Gestor de votante");

        numeroVota.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numeroVota.setForeground(new java.awt.Color(255, 0, 0));
        jScrollPane2.setViewportView(numeroVota);

        jLabel2.setText("Votante n°");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(votarCandi))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(img_registraduria)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(candiRegistrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(img_registraduria)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(candiRegistrado, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(votarCandi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void votarCandiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_votarCandiActionPerformed

        this.candiRegistrado.setSelectedIndex(0);
        int columna = 2;
        int fila = this.tablaVotar.getSelectedRow();
        String id = this.tablaVotar.getValueAt(fila, columna).toString();

        ClsCandidato candidato = this.buscarCandidato(id);

        if (candidato != null) {

            ClsVotante votante = this.buscarVotante(this.numeroVota.getText());
            String cc = this.numeroVota.getText();
            String nombre = "";
            String telefono = "";
            String correo = "";
            String ciudad = "";
            String cotrasena = "";
            int valor = 1;
            int vc=1;

            if (votante != null) {
                for (ClsVotante c : this.listaVotantes) {
                    String d = String.valueOf(c.getCedula());
                    if (numeroVota.getText().equals(d)) {
                        
                        if (c.getEstado() == 0){
                            ClsVotante voto = new ClsVotante(cc, nombre, telefono,
                                    correo, ciudad, cotrasena, valor);
                            this.controladorVotante.actualizarVoto(voto);
                            
                            for (ClsCandidato da: this.listaCandidatos){
                                  if (da.getCedula().equals(id)) {
                                      vc=vc+da.getVoto();
                                       ClsCandidato candi = new ClsCandidato (da.getCedula(),da.getNombre(), da.getTelefono(),da.getPartidoPoliticoCandidato(),da.getCiudad(),da.getBiografiaCandidato(),da.getSmsCampana(),da.getPropuestaCandidato(), vc);
                                       this.controladorcandidato.actualizarVotoCandidato(candi);
                                  }
                            }
                          
                                                        
                            this.dispose();
                            this.FrameMenu.setVisible(true);

                        } else {
                          JOptionPane.showMessageDialog(null, "Usted ya votó");
                          this.dispose();
                          this.FrameMenu.setVisible(true);

                        }
                       
                    } else {
                        

                    }

                }
       
            }
        }
    }//GEN-LAST:event_votarCandiActionPerformed

    public ClsVotante buscarVotante(String cedula) {

        for (ClsVotante c : this.listaVotantes) {
            if (cedula.equals(c.getCedula())) {
                return c;
            }
        }
        return null;
    }

    public ClsCandidato buscarCandidato(String cedula) {

        for (ClsCandidato c : this.listaCandidatos) {
            if (cedula.equals(c.getCedula())) {
                return c;
            }
        }
        return null;
    }

    public void llamarvotante() {
        this.listaVotantes = this.controladorVotante.llamarvotante();

    }


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.dispose();
        this.FrameMenu.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    public void llamarcandidato() {
        this.listaCandidatos = this.controladorcandidato.llamarcandidato();
        this.actualizar_tabla_candidato(listaCandidatos);
    }

    private void actualizar_tabla_candidato(LinkedList<ClsCandidato> candidatos) {
        DefaultTableModel modelo = (DefaultTableModel) this.tablaVotar.getModel();
        modelo.setRowCount(0);
        for (ClsCandidato i : candidatos) {
            Object[] fila = {i.getNombre(), i.getPartidoPoliticoCandidato(), i.getCedula(), i.getSmsCampana()};//esto es paras tener la info organizada
            modelo.addRow(fila); //agregar la  informacion a la tabla    
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameVotar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameVotar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameVotar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameVotar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameVotar(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane candiRegistrado;
    private javax.swing.JLabel img_registraduria;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane numeroVota;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tablaVotar;
    private javax.swing.JButton votarCandi;
    // End of variables declaration//GEN-END:variables
}
